#pragma once

typedef enum
{
    // Single-character tokens.
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS,
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
    TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,

    // One or two character tokens.
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,

    // added later
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,

    // Literals.
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

    // Keywords.
    TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
    TOKEN_FOR, TOKEN_FUNC, TOKEN_IF, TOKEN_NULL, TOKEN_OR,
    TOKEN_PRINT, TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
    TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE,

    // added later
    TOKEN_VOID,
    TOKEN_STATIC,
    TOKEN_ELIF,
    TOKEN_BREAK, TOKEN_CONTINUE,
    TOKEN_USING,
    TOKEN_PROPERTY,

    // error and eof
    TOKEN_ERROR, TOKEN_EOF
} TokenType;

/*
-- list of tokens not implemented (they have no effect) --
TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
TOKEN_COMMA, TOKEN_DOT,
TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
TOKEN_SEMICOLON,

TOKEN_BANG, TOKEN_BANG_EQUAL,
TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
TOKEN_GREATER, TOKEN_GREATER_EQUAL,
TOKEN_LESS, TOKEN_LESS_EQUAL,

TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL,
TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,

TOKEN_IDENTIFIER, TOKEN_STRING,

TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
TOKEN_FOR, TOKEN_FUNC, TOKEN_IF, TOKEN_NULL, TOKEN_OR,
TOKEN_PRINT, TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE,

TOKEN_VOID,
TOKEN_STATIC,
TOKEN_ELIF,
TOKEN_BREAK, TOKEN_CONTINUE,
TOKEN_USING,
TOKEN_PROPERTY
TOKEN_RETURN has a placeholder implementation
*/

typedef struct Token
{
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

void initScanner(const char* source);
Token scan();